# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 590353563b70155dbab5633a0cecf2307aa625acdface80dfe843bd3b9516ef898cf76d063d08a07f5c95a07e4ad6f5656e0fd963fc526523e400b7a4b0d7925

test:
  secret_key_base: 077fd4ea725b6191721fdfe69be523e329c92d364f7987b4d143225371d377b55e0f363995def2e21bd60a6724e914a0c9c6c969365b6e1ff9d56d2a8f8126ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
